tunnel: your-tunnel-id
credentials-file: /root/.cloudflared/your-tunnel-id.json

ingress:
  # API Gateway - Main API endpoints
  - hostname: vexa.5173322.xyz
    service: http://api-gateway:8000
    originRequest:
      httpHostHeader: vexa.5173322.xyz
      
  # Admin API - User management
  - hostname: admin.vexa.5173322.xyz
    service: http://admin-api:8001
    originRequest:
      httpHostHeader: admin.vexa.5173322.xyz
      
  # Transcription Collector - Direct access for debugging
  - hostname: transcripts.vexa.5173322.xyz
    service: http://transcription-collector:8000
    originRequest:
      httpHostHeader: transcripts.vexa.5173322.xyz
      
  # Traefik Dashboard - Optional monitoring
  - hostname: traefik.vexa.5173322.xyz
    service: http://traefik:8080
    originRequest:
      httpHostHeader: traefik.vexa.5173322.xyz
      
  # Catch-all rule (required)
  - service: http_status:404